### PR TITLE
Fix a couple of issues

### PR DESCRIPTION
**Pull request by ghost**
Hi!

Thank you for the package. With this PR I propose to fix a couple of issues:

- There currently exists a race condition where `self.dup_fd` may be closed by the `printer thread` while the thread that calls `def close` still wants to duplicate the `self.dup_fd` to `self.fd`.
- The thread that calls `def  close` should wait for the `printer thread` to join to make sure that all data which is read ends up in `writer` before closing the StreamCapture filedescriptors and redirecting the original file descriptors back.
- It may be possible that the magic value is interspliced between some logging. We should write all segments that have been read.
- It is currently not possible to use the same `writer` for multiple `StreamCapture` objects as the `StreamCapture` object will close `writer` on `def close`. Also, this violates best practices where the `writer` object should be closed by the initiating component; `StreamCapture` is not in charge of the lifecycle of `writer`.

I have added a couple of tests to show that it went wrong before these changes, but they are now fixed.

On a side note, would you accept changes to add type hinting as well as format the file according to pep8 and other standards?

Thanks!

### CODE REVIEW

**Comment by lfse-repo** [comment]
Merging Github accounts, please, refer to @lfse-slafleur for further processing.

**Comment by lfse-slafleur** [comment]
> Merging Github accounts, please, refer to @lfse-slafleur for further processing.

This account is taking over. Apologies for the unnecessary notifications.

**Comment by lfse-slafleur** [comment]
@sloisel Are you still actively maintaining this repository? Otherwise I wouldn't mind forking if you can help out with granting access to Pypi and such.

**Review by sloisel — APPROVED** [review]
Sorry, I'm bad at Github and only just now saw your PR.

**Pull request merged**
